### ISSUE TITLE
Error: option 'device' required even for network devices?

### ISSUE THREAD

**Issue by Stadicus** [mercenaruss/zigstar_addons#15]
I'm trying to flash the ZigStar UZG device (version 0.3) with the CC1352P7 chip according to their instructions. First I tried using the ZigStar Multitool (that does not seem to support CC1352P7 according to https://github.com/xyzroe/ZigStarGW-MT/issues/22). As recommended, I'm now trying to flash the UZG with the ZigStar Home Assistant addon, following the [official UZG instructions](https://uzg.zig-star.com/flashing-and-updating/#ha-addon-ethernet).

I installed the **ZigStar TI CC2652P7 Flasher Add-on**, which seems suited to the job according to https://github.com/mercenaruss/zigstar_addons/commit/7c9327db5895db52ee1641af288401c65abca632.

I enter all relevant information into the configuration form, but then I get the following error message on save:

> Failed to save add-on configuration, Missing required option 'device' in ZigStar TI CC2652P7 FW Flasher (193f5383_zigstar-cc2652p7-flasher). Got {'device': None, 'network_device': '192.168.1.5:6638', 'usb_mode': False, 'coordinator_fw': False, 'router_fw': False, 'firmware_url': 'https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P7_coordinator_20230507.zip', 'trigger_bsl': True}

![grafik](https://github.com/mercenaruss/zigstar_addons/assets/19550140/80e46239-0318-4357-b9a3-f2662dd9eaab)

Checking the YAML configuration, I see that the argument `device` is expected and is configured with `null`. This seems to be only relevant for USB devices, and I can't select anything because the UZG is connected via Ethernet.

```YAML
device: null
network_device: 192.168.1.5:6638
usb_mode: false
coordinator_fw: false
router_fw: false
firmware_url: >-
  https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P7_coordinator_20230507.zip
trigger_bsl: true
```

Any recommendation how I can get this to work?
